### ISSUE TITLE
Include an image in a comment

### ISSUE THREAD

**Issue by bpbond** [wow-actions/auto-comment#15]
Hi, thanks for this useful bot. I'm interested in including an image in the auto-comment (e.g. PR diagnostics, generated from a script that's run in an earlier job in the workflow). Is this possible?

### Expected Behavior

Something like this (just in terms of there being a comment with an image, don't mean Codecov specifically):
![Screen Shot 2021-09-29 at 12 32 58 PM](https://user-images.githubusercontent.com/1956468/135311064-66d0afc0-2915-46b8-9e7f-aef37829538b.png)

### Possible Solution

I've done a lot of googling, but haven't found a good solution—would welcome advice!

### Additional Context

Thank you! cc @leeyap

**Comment by bubkoo** [comment]
Hi, @urish The earlier job should output the image url, then we can embed the image in the comment.

ref: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idoutputs

```yml
name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: xxx/action-to-generate-images
         id: images
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            Thank you for raising your pull request.
            ![image](${{ steps.images.outputs.url }})
```
