### ISSUE TITLE
Comment on transferred issues does not appear to be working

### ISSUE THREAD

**Issue by t-eckert** [wow-actions/auto-comment#17]
### Expected Behavior

I set up a [GitHub action](https://github.com/hashicorp/consul-k8s/blob/main/.github/workflows/issue-context-bot.yml) to comment on issues which were transferred to the repository. When an issue is transferred, it should comment on the issue with a request for more context.

### Current Behavior

The action is triggered, but the comment is never posted. The action succeeds.

### Possible Solution

I may have implemented the action incorrectly. Here is the implementation:

``` yaml
name: Issue Context Bot

on: [issues]

jobs:
  add-context:
    runs-on: ubuntu-latest
    steps:
    - uses: wow-actions/auto-comment@v1.0.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        issuesTransferred: |
          "Hi @{{ author }},
          
          It looks like your issue has been transferred to the Consul on Kubernetes repository.
          If your issue is a question or bug report, there is some additional context that will
          help us solve your issue. Please reply with the following information if it is not
          included in your original issue:
          
          - the [Helm values](https://www.consul.io/docs/k8s/helm) you used to install Consul
          on Kubernetes
          - the version of Consul on Kubernetes used
          - the version of Kubernetes you are using
          - if you installed Consul on Kubernetes using Helm or the Consul-K8s CLI"
```

### Steps To Reproduce

Here is an example of an issue which was transferred to the repository yet did not get the comment added: https://github.com/hashicorp/consul-k8s/issues/1054
