### ISSUE TITLE
Comment when PR is merged

### ISSUE THREAD

**Issue by reveurguy** [wow-actions/auto-comment#22]
Hii 
I want to add an auto-comment when the PR is merged, is there any way to do that?

**Comment by reveurguy** [comment]
Also the comment when PR is closed is not working. When PR is opened, the comment is working fine

**Comment by bubkoo** [comment]
@reveurguy 

Explicitly specify the PR `"closed"` event is work for me. 
And `"merged"` event is supported in this [PR](#26).
Try the following configuration:

```yml
name: Auto Comment
on:
  pull_request:
    types: [closed]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          pullRequestClosed: >
            👋 @{{ author }} This PR is closed.

          pullRequestMerged: >
            👋 @{{ author }} This PR is merged.

```
